#!/usr/bin/ruby
require 'net/ftp'
def ftp_read_file
  ftp = Net::FTP.new('192.168.31.97',port: 2121) #ftp地址
  ftp.passive = true
  ftp.login('dccmmtop','dccmmtop')#ftp账号 密码

  if File.file? ARGV[0]
      puts "uploading #{ARGV[0]}"
      ftp.put(ARGV[0])
  elsif File.directory? ARGV[0]
    path = ARGV[0]
    Dir.open(path).each do |file|
      next unless File.file? file
      puts "uploading #{file}"
      ftp.put(file)
    end
  end
  ftp.close
end
ftp_read_file
